name: BANedetta-vk-posts
version: 1-dev
api: 5.0.0
main: Taskov1ch\BANedetta_VK\VkPosts
depend: BANedetta

permissions:
  banedetta.vk.add_admin:
    default: op

  banedetta.vk.remove_admin:
    default: op

  banedetta.vk.admins:
    default: op
